config/routes.rb
Rails.application.routes.draw do
  devise_for :user_models   #users devise
  resources :users          #friends
  # get 'home/index'
  #root 'home#index'
  root 'users#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord #friend
	belongs_to :user_model
end

app/models/user_model.rb
class UserModel < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end


  def about 

    @about_me = "My name is Lela" #instance variable
    @answer = 2 + 2
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user_model!, except: [:index, :show] #if user is not auth don't let him do anything except index and show
  before_action :correct_user, only: [:edit, :update, :destroy] #look up and see, before any of actions, make sure if it's correct user but only for edit, upd, del


  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    #@user = User.new
    @user = current_user_model.users.build
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    #@user = User.new(user_params)
    @user = current_user_model.users.build(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @user = current_user_model.users.find_by(id: params[:id])
    redirect_to users_path, notice: "Not authorized to edit this user" if @user.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :twitter, :user_model_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "UMS App", root_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "About us", home_about_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add User", new_user_path, class:"nav-link" %>
      </li>


    <% if user_model_signed_in? %>
     <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_model_registration_path, class:"nav-link" %>
      </li>
        <li class="nav-item">
        <%= button_to "Sign Out", destroy_user_model_session_path, method: :delete, class:"nav-link", style:"background-color:#6B6E70;"  %>
      </li>

      <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_model_registration_path, class:"nav-link" %>

      </li>
        <li class="nav-item">
        <%= link_to "Sign In", new_user_model_session_path, class:"nav-link" %>
      </li>    
      <% end %> 

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us...Basic Page</h1>
<p>
	<%= @about_me %>
</p>

<p>
	2 + 2 = <%= @answer %>
</p>

app/views/home/index.html.erb
<h1>Hellloooo</h1>
This is my first rails page..

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>UMS App</title>  

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
  <body>

    <%= render "home/navbar"%>

    <div class="container">
      <br> 
      <% if notice %>
         <%= render "layouts/alerts"%>
       <% end %>

      <br>
      <%= yield %>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First name" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last name" %>
  </div>

  <div class="field form-group">
    <%= form.label :email%>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, class:"form-control", placeholder:"Phone number" %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_model_id, id: :user_user_model_id, class:"form-control", value:current_user_model.id, type: :hidden %>
  </div>
  <br>


  <div >
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= user.phone_number %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= user.twitter %>
  </p>
  <br>
  <br>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div class="table">
  <%= link_to "Show this user", @user, class:"btn btn-primary"  %>
  <%= link_to "Back to users", users_path, class:"btn btn-secondary" %>

</div>

app/views/users/index.html.erb
<h1>Users List</h1>
<br>

<% if user_model_signed_in?%>
<table class="table table-striped table-bordered table-hover">
  <thead bgcolor="#5AA1E3">
    <tr>
      <th>User</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Twitter</th>

      <th class="text-center", colspan="3">CRUD</th>
    </tr>
  </thead>
<tbody>

<div id="users">
  <% @users.each do |user| %>
    <!-- <%= render user %> -->
      <% if user.user_model == current_user_model %>
      <tr>
      <td> <%= link_to user.first_name + ' ' + user.last_name, user %> </td>
      <td> <%= user.email %> </td>
      <td> <%= user.phone_number %> </td>
      <td> <%= user.twitter %> </td>


      <td> <%= link_to "Show", user, class:"btn btn-outline-secondary" %> </td>

      <td> <%= link_to "Edit", edit_user_path(user), class:"btn btn-outline-info" %> </td>
      <td> <%= button_to "Delete", user, method: :delete, class:"btn btn-outline-danger btn-sm" %> </td>
  
    </tr>
    <% end %>
  <% end %>
</div>

</tbody>
</table>

<br>

<%= link_to "New user", new_user_path, class:"btn btn-secondary" %>

<% else %>
<h1>Hellloooo</h1>
This is my first rails page..

<% end %>

app/views/users/new.html.erb
<h1>Add new user</h1>

<%= render "form", user: @user %>

<br>

<div> <%= link_to "Back to users", users_path, class:"btn btn-secondary" %> </div>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @user.first_name %>
    <%= @user.last_name %>
  </h1>

  <p class="lead">
    <%= @user.email %>
  </p>
  <br>

<%= render @user %>

<form class="form-inline">
  <div class="form-group", id="show-buttons">
   <%= link_to "Edit", edit_user_path(@user), class:"btn btn-primary" %> 
  </div>
  <div class="form-group", id="show-buttons">
    <%= button_to "Delete", @user, method: :delete, data: {confirm: "Are you sure?" }, class:"btn btn-danger" %>
  </div>
  <br>
  <div class="form-group", id="show-buttons">
    <%= link_to "Back to users", users_path, class:"btn btn-secondary" %>
  </div>

</form>
 

</div>